@startuml
title Administrative enheter kommuner - Objekttyper

skinparam class {
  AttributeIconSize 0
}

package "Objekttyper" {

  class Arealregnskap <<featureType>> {
    + område [1] : GM_MultiSurface
    + arealdekke [1] : Arealdekke
    + oppdateringsdato [1] : Date
    + treslag [0..1] : Treslag
    + skogbonitet [0..1] : ArealressursSkogbonitet
    + grunnforhold [1] : ArealressursGrunnforhold
    + arealbrukHovedklasse [0..1] : SsbArealbrukHovedklasse
    + arealbrukUnderklasse [0..1] : SsbArealbrukUnderklasse
    + havarealbrukStedbundet [0..1] : ArealbrukHav
    + havfiskeribruk [0..1] : HavFiskeriBruk
    + okosystemtype1 [1] : Okosystemtype1
    + okosystemtype2 [0..1] : Okosystemtype2
    + okosystemtype3 [0..1] : Okosystemtype3
    + okosystemtypeKode [1] : CharacterString
    + grunnkartKilde [1] : GrunnkartKilde
    + ssbarealbrukKilde [0..1] : CharacterString
    + kommunenummer [1] : Kommunenummer
    + identifikasjon [1] : Identifikasjon
    + arealM2 [1] : Real
    + omkrets [1] : Real
    + bruktflagg [1] : Integer
  }

  class Identifikasjon {
    + lokalId [1] : CharacterString
    + navnerom [1] : CharacterString
    + versjonId [0..1] : CharacterString
  }
}

@enduml
